CREATE DATABASE UNIVERSITY;
USE UNIVERSITY;

CREATE TABLE STUDENT(
ID INT IDENTITY PRIMARY KEY,
NAME VARCHAR(30) NOT NULL,
CONTACT VARCHAR(30) NOT NULL,
DEPARTMENT VARCHAR(30) NOT NULL,
YEAR VARCHAR(10) NOT NULL);
SELECT * FROM STUDENT;

CREATE TABLE COURSE(
ID int NOT NULL,
COURSE_Name VARCHAR(30) NOT NULL,
YEAR VARCHAR(10) NOT NULL,
);
SELECT * FROM COURSE;


INSERT INTO STUDENT(NAME,CONTACT,DEPARTMENT,YEAR) VALUES
('PRASANNA','9703088064','ELCTRONICS','2019'),
('RESHMA','9087561231','COMPUTER','2017'),
('ARJUN','6005526294','CIVIL','2018'),
('LAKSHMI','9876543212','ELECTRICAL','2020');
SELECT * FROM STUDENT;
INSERT INTO STUDENT(NAME,CONTACT,DEPARTMENT,YEAR) VALUES
('VARA','9049874563','AERONATICAL','2013');

INSERT INTO COURSE(ID,COURSE_Name,YEAR) VALUES
('1','PYTHON','2019'),
('2','ADVANCED JAVA','2017'),
('1','DATA STRUCTURE','2018'),
('4','BASIC ELECTRONICS','2020'),
('3','HTML','2015');
SELECT * FROM COURSE;
INSERT INTO COURSE(ID,COURSE_Name,YEAR) VALUES
('5','C SHARP','2016'),
('2','ADVANCED ELECTRICALS','2014');

--Inner Join
SELECT ST.NAME, CR.COURSE_Name
FROM STUDENT ST JOIN COURSE CR
ON ST.ID = CR.ID;

--Left Join
SELECT ST.NAME, CR.COURSE_Name
FROM STUDENT ST LEFT JOIN COURSE CR
ON ST.ID = CR.ID;

--Right Join
SELECT ST.NAME, CR.COURSE_Name
FROM STUDENT ST RIGHT JOIN COURSE CR
ON ST.ID = CR.ID;

--Full Join
SELECT ST.NAME, CR.YEAR
FROM STUDENT ST FULL JOIN COURSE CR
ON ST.ID = CR.ID;

--Cross Join
SELECT ST.NAME, CR.COURSE_Name
FROM STUDENT ST CROSS JOIN COURSE CR;



SELECT * FROM STUDENT;
SELECT * FROM COURSE;

--  One to One Relation----------
ALTER TABLE COURSE ADD CONSTRAINT FK_STUDENT FOREIGN KEY(ID) REFERENCES STUDENT(ID) ON DELETE CASCADE;
DELETE FROM STUDENT WHERE NAME='PRASANNA';
SELECT * FROM STUDENT
-----2NF------------
CREATE TABLE COURSE_NAME1(
COURSE_ID INT IDENTITY PRIMARY KEY,
YEAR varchar(30));

CREATE TABLE ID(
STUDENT_ID varchar(30) not null,
COURSE_ID varchar(30));

SELECT * FROM COURSE_NAME1;
SELECT * FROM ID; 
INSERT INTO COURSE_NAME1(COURSE_ID, YEAR) VALUES ('1','2015'), ('2', '1998'),
('3', '2010'), ('4', '2022');

INSERT INTO ID(STUDENT_ID, COURSE_ID) VALUES ('152M1A0403','1'), ('163M1A0406', '2'),
('173M1A0403','3'), ('183M1A0408', '4')

ALTER TABLE STUDENT ADD CONSTRAINT FK_COURSE_NAME1 FOREIGN KEY(YEAR) REFERENCES COURSE_NAME1(YEAR) ON DELETE CASCADE;
ALTER TABLE ID ADD CONSTRAINT FK_STUDENT FOREIGN KEY(COURSE_ID) REFERENCES STUDENT(ID) ON DELETE CASCADE;
ALTER TABLE COURSE ADD CONSTRAINT FK_COURSE_NAME1 FOREIGN KEY(YEAR) REFERENCES COURSE_NAME1(YEAR) ON DELETE CASCADE;

--------SUBQUIRY---------------
SELECT * FROM STUDENT
SELECT NAME, DEPARTMENT FROM STUDENT WHERE DEPARTMENT IN ('ELCTRONICS');
SELECT NAME, DEPARTMENT FROM STUDENT WHERE DEPARTMENT NOT IN ('CIVIL');
------INDEX---------
CREATE INDEX IDX_DEPARTMENT
ON STUDENT (DEPARTMENT);
SELECT * FROM STUDENT
INSERT INTO STUDENT(NAME,CONTACT,DEPARTMENT,YEAR) VALUES
('CHITTI','9182147305','CIVIL','2022');
INSERT INTO STUDENT(NAME,CONTACT,DEPARTMENT,YEAR) VALUES
('JAGADEESH','9184567789','IT','2021');
CREATE UNIQUE INDEX INDEX_NAME ON STUDENT (NAME);
INSERT INTO STUDENT(NAME,CONTACT,DEPARTMENT,YEAR) VALUES
('CHITTI','9182147305','IT','2022');
CREATE UNIQUE INDEX INDEX_DEPARTMENT ON STUDENT (DEPARTMENT);

-------VIEWS------------
CREATE VIEW STUDENT_VIEW AS SELECT NAME, DEPARTMENT FROM STUDENT WHERE NAME = DEPARTMENT;

SELECT * FROM STUDENT_VIEW;
---------TRIGGERS-------
DROP TRIGGER IF EXISTS t_STUDENT_INSERT;
GO
CREATE TRIGGER t_STUDENT_INSERT ON STUDENT INSTEAD OF INSERT
AS BEGIN
    DECLARE @NAME VARCHAR(128) 
    DECLARE @CONTACT VARCHAR(128)
    DECLARE @DEPARTMENT VARCHAR(128)
    DECLARE @YEAR VARCHAR(10) 
    SELECT @NAME = NAME, @CONTACT = CONTACT, @DEPARTMENT = DEPARTMENT, @YEAR = YEAR FROM INSERTED
    IF '@NAME' IS NULL SET @NAME = '@CONTACT'
    IF '@CONTACT' IS NULL SET @CONTACT = '@DEPARTMENT'
    IF '@DEPARTMEN' IS NULL SET @DEPARTMENT = '@YEAR'
	IF '@YEAR' IS NULL SET @YEAR = '@NAME'
    INSERT INTO STUDENT (NAME, CONTACT, DEPARTMENT, YEAR) VALUES ('@NAME', '@CONTACT', '@DEPARTMENT',' @YEAR');
END
SELECT * FROM STUDENT;
INSERT INTO STUDENT(NAME, CONTACT,DEPARTMENT,YEAR) VALUES ('KATHI', '6543212345','IT','2011');
SELECT * FROM STUDENT;


------STORED PROCEDURE------------
CREATE PROCEDURE STUDENTTables (@NAME VARCHAR(30),@CONTACT varchar(30),@DEPARTMENT varchar(30),@YEAR VARCHAR(10))
AS
BEGIN
SET NOCOUNT ON; 
INSERT INTO STUDENT([NAME],[CONTACT],[DEPARTMENT],[YEAR]) VALUES (@NAME,@CONTACT,@DEPARTMENT,@YEAR)
END
GO
SELECT * FROM STUDENT

EXEC [dbo].[STUDENTTables] @NAME='KATHI',@CONTACT ='9876543212',@DEPARTMENT ='SALES',@YEAR = '2012';
GO
SELECT * FROM STUDENT